module.exports = {
    deaths : require("./deaths"),
    event : require("./event"),
    events : require("./events"),
    guild : require("./guild"),
    guildData : require("./guilddata"),
    gvg : require("./gvg"),
    kills : require("./kills"),
    pastGvg : require("./pastGvgs"),
    player : require("./player"),
    search : require("./search"),
    solokills : require("./soloKills"),
    topKills : require("./topKills"),
    upcomingGvgs : require("./upcomingGvgs"),
    topPvpGuild: require('./topPvpGuild'),
    topPveGuild: require('./topPveGuild'),
    topCraftingGuild: require('./topCraftingGuild'),
    topGatheringGuild: require('./topGatheringGuild'),
    battles: require('./battles'),
    battle: require('./battle')
}
